### ISSUE TITLE
Meters <-> Centimeters Conversion

### ISSUE THREAD

**Issue by michaelwro** [michaelwro/math-utils#31]
Create a meters <-> centimeters conversion function.

Also:

- fix namespace comment order [HERE](https://github.com/michaelwro/math-utils/blob/main/include/conversions.h#L294)
- remove [THIS](https://github.com/michaelwro/math-utils/blob/main/include/conversions.h#L195) commented out code.

**Comment by yashwardhan-jyani** [comment]
@michaelwro 
I created the meter <-> centimeter conversion you wanted but what do you want in the namespace comments?
Do you want them in opposite orders?

Also can I make more commits to an existing PR or do I have to make another one? I'm new to Github!!

**Comment by michaelwro** [comment]
Thanks for the help @yashwardhan-jyani.

I have my closing namespace comments in the wrong order. Should be this:

```cpp
namespace MathUtils { namespace Conversions {
...
}  // namespace Conversions
}  // namespace MathUtils
```

PR's are just saying "I want to merge this *branch* into the main branch. You can create another commit on your branch and it'll be part of the original PR. No need to make another one.
